[packaging]
auto_update = false
package_name = "azure-oep-file"
package_pprint_name = "Azure Oep File"
is_stable = false
is_arm = false

# Package owners should uncomment and set this doc id.
# package_doc_id = "oep-storage"